/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// AssetIssueRequest Request for generation of asset issue transaction
type AssetIssueRequest struct {
	// Encoded Ergo Address
	Address *string `json:"address,omitempty"`
	// Optional, amount of ergs to be put into box with issued assets
	ErgValue *int64 `json:"ergValue,omitempty"`
	// Supply amount
	Amount int64 `json:"amount"`
	// Assets name
	Name string `json:"name"`
	// Assets description
	Description string `json:"description"`
	// Number of decimal places
	Decimals int32 `json:"decimals"`
	// Ergo box registers
	Registers *map[string]string `json:"registers,omitempty"`
}
