/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// AvlTreeData struct for AvlTreeData
type AvlTreeData struct {
	// Base16-encoded 32 byte digest
	Digest      string `json:"digest"`
	TreeFlags   *int32 `json:"treeFlags,omitempty"`
	KeyLength   *int32 `json:"keyLength,omitempty"`
	ValueLength *int32 `json:"valueLength,omitempty"`
}
