/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// BlockAdProofs struct for BlockAdProofs
type BlockAdProofs struct {
	// Base16-encoded 32 byte modifier id
	HeaderId string `json:"headerId"`
	// Base16-encoded ad proofs
	ProofBytes string `json:"proofBytes"`
	// Base16-encoded 32 byte digest
	Digest string `json:"digest"`
	// Size in bytes
	Size int32 `json:"size"`
}
