/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// DlogCommitment Randomness and commitment for the first step of the Schnorr protocol
type DlogCommitment struct {
	// Hex-encoded big-endian 256-bits secret exponent
	R string `json:"r"`
	// Hex-encoded \"g\" generator for the Diffie-Hellman tuple (secp256k1 curve point)
	A string `json:"a"`
}
