/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// Extension struct for Extension
type Extension struct {
	// Base16-encoded 32 byte modifier id
	HeaderID string `json:"headerId"`
	// Base16-encoded 32 byte digest
	Digest string `json:"digest"`
	// List of key-value records
	Fields *[][]string `json:"fields"`
}
