/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// SerializedBox struct for SerializedBox
type SerializedBox struct {
	// Base16-encoded transaction box id bytes. Should be 32 bytes long
	BoxId string `json:"boxId"`
	// Base16-encoded bytes
	Bytes string `json:"bytes"`
}
