/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// SpendingProof Spending proof for transaction input
type SpendingProof struct {
	// Base16-encoded spending proofs
	ProofBytes string `json:"proofBytes"`
	// Variables to be put into context
	Extension map[string]string `json:"extension"`
}
