/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// UnsignedErgoTransaction Unsigned Ergo transaction
type UnsignedErgoTransaction struct {
	// Base16-encoded transaction id bytes
	Id *string `json:"id,omitempty"`
	// Unsigned inputs of the transaction
	Inputs *[]ErgoTransactionUnsignedInput `json:"inputs"`
	// Data inputs of the transaction
	DataInputs *[]ErgoTransactionDataInput `json:"dataInputs"`
	// Outputs of the transaction
	Outputs *[]ErgoTransactionOutput `json:"outputs"`
}
