/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// AddressHolder Holds encoded ErgoAddress
type AddressHolder struct {
	// Encoded Ergo Address
	Address string `json:"address"`
}
