/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// APIError struct for APIError
type APIError struct {
	// Error code
	Error int32 `json:"error"`
	// String error code
	Reason string `json:"reason"`
	// Detailed error description
	Detail string `json:"detail"`
}
