/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// EmissionInfo Emission info for height
type EmissionInfo struct {
	MinerReward      *int64 `json:"minerReward,omitempty"`
	TotalCoinsIssued *int64 `json:"totalCoinsIssued,omitempty"`
	TotalRemainCoins *int64 `json:"totalRemainCoins,omitempty"`
}
