/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// GenerateCommitmentsRequest request to generate commitments to sign a transaction
type GenerateCommitmentsRequest struct {
	Tx      *UnsignedErgoTransaction           `json:"tx"`
	Secrets *GenerateCommitmentsRequestSecrets `json:"secrets,omitempty"`
	// Optional list of inputs to be used in serialized form
	InputsRaw *[]string `json:"inputsRaw,omitempty"`
	// Optional list of inputs to be used in serialized form
	DataInputsRaw *[]string `json:"dataInputsRaw,omitempty"`
}
