/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// PaymentRequest Request for generation of payment transaction to a given address
type PaymentRequest struct {
	// Encoded Ergo Address
	Address string `json:"address"`
	// Payment amount
	Value int64 `json:"value"`
	// Assets list in the transaction
	Assets *[]Asset `json:"assets,omitempty"`
	// Ergo box registers
	Registers *map[string]string `json:"registers,omitempty"`
}
