/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// PeerInfo struct for PeerInfo
type PeerInfo struct {
	Address string    `json:"address"`
	Mode    *PeerMode `json:"mode"`
	Version string    `json:"version"`
	Status  string    `json:"status"`
	Height  int32     `json:"height"`
}
