/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// Peer struct for Peer
type Peer struct {
	Address string  `json:"address"`
	Name    *string `json:"name,omitempty"`
	// Basic timestamp definition
	LastSeen       *int64  `json:"lastSeen,omitempty"`
	ConnectionType *string `json:"connectionType,omitempty"`
}
