/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.20.2
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo

// SourceHolder struct for SourceHolder
type SourceHolder struct {
	// Sigma source to be compiled
	Source string `json:"source"`
}
