name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
          # For some reason this can run really really slow in CI
          # https://github.com/golangci/golangci-lint-action/issues/308
          args: --timeout=3m
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: make test
# Enable when cross compilation is working: https://github.com/ross-weir/rosetta-ergo/issues/15
#  # Ensure the project builds on all targets
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: actions/setup-go@v2
#        with:
#          go-version: 1.17
#      - name: Create release
#        uses: goreleaser/goreleaser-action@v2
#        with:
#          version: latest
#          args: build
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}