name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
          # For some reason this can run really really slow in CI
          # https://github.com/golangci/golangci-lint-action/issues/308
          args: --timeout=3m
